### PR TITLE
Fix neovim output error

### PR DESCRIPTION
**Pull request by dihak**

### CODE REVIEW

**Comment by thosakwe** [comment]
Before I can merge this, I'll need to know which output error you were getting before, and how to reproduce it.

**Comment by dihak** [comment]
Ah, i forgot to write the error., i will give you a detail later

**Comment by ghost** [comment]
That was before of this pr on neovim

Screenshot_2

This one is when i changed with this pr on neovim
Screenshot_1

It fixed the output formatting problem on neovim

**Comment by thosakwe** [comment]
Merged. Thanks for the PR!

**Pull request merged**
