### PR TITLE
Feature/merge windows job error (manually merged)

### PR DESCRIPTION
**Pull request by datsuns**
manually merged pull request into latest master.
merged pull request: https://github.com/thosakwe/vim-flutter/pull/17

thanks for @gabr !

p.s.
  maybe this approach, manually merged by other person, is bad way...
  i'm not familiar with GitHub culture.
  if you have another good approach, please tell me !

### CODE REVIEW

**Comment by insidewhy** [comment]
@datsuns Thanks for this work, I'll add windows support very shortly, if you could help me verify it works (I don't use windows) that would be great!

**Comment by datsuns** [comment]
@insidewhy thanks! I can do that ! I'm using windows.

**Comment by insidewhy** [comment]
@datsuns I've added this to my branch now, you can try `insidewhy/vim-flutter`. The commit that implements it is here:

https://github.com/insidewhy/vim-flutter/commit/15c9cb5db4a22832801614d0007b619cc0319f6c

**Comment by insidewhy** [comment]
This functionality is upstream now.

**Pull request closed without merging**
