### PR TITLE
Add g:flutter_autoscroll option

### PR DESCRIPTION
**Pull request by insidewhy**
- Add g:flutter_autoscroll option

### CODE REVIEW

**Comment by guildem** [comment]
Nice one !
For a `vim` version, you could use something like (untested yet) : 
```
call win_execute(BUF_WIN_ID, ['call setpos(".", [BUM_NUM, LINE_NUM, 1, 1])', 'redraw'])
```

**Comment by insidewhy** [comment]
Merged manually

**Comment by guildem** [comment]
@insidewhy Do you want me to try a PR for vim version ?

**Comment by insidewhy** [comment]
@guildem All PRs welcome!

**Pull request closed without merging**
