### PR TITLE
Added flutter attach command

### PR DESCRIPTION
**Pull request by guildem**
This command is very useful when implementing flutter into an existing android/ios native app.
I added specific log parameter for this command.

### CODE REVIEW

**Review by helielson — APPROVED** [review]
Great!!! It works like a charm 🚀

**Comment by guildem** [comment]
Rookie github user here, do I need to do something to merge my changes upstream ?

**Comment by guildem** [comment]
With some delay, I fixed conflicts. You may merge this PR now.

**Comment by insidewhy** [comment]
@thosakwe Hi, are you still maintaining this? If not, could you add me as a maintainer? This PR has been hanging around for almost 2 years and it's a great change.

**Comment by insidewhy** [comment]
@guildem I'd probably change this a little to make `flutter#run` and `flutter#attach` both share the same function call, there's a lot of copy and paste in this code. I'll probably implement that tomorrow on my fork.

**Comment by guildem** [comment]
@insidewhy I added some changes made on run method to attach method, in case you want to work on the lastest version, I pushed it. It sure would be better to get factored code, but i'm not a vim script expert and I don't know what to do with the 2 global parameters used. Feel free to work on it, and if we have an answer from @thosakwe we will see how we can do to merge a good PR.

**Comment by thosakwe** [comment]
@insidewhy I don't do any open-source work these days. I'd be glad to add you as a maintainer.
@guildem Thanks for the PR - is it ready to be merged?

**Comment by insidewhy** [comment]
@thosakwe Thanks, let me know when you've added me, I've made several improvements to the plugin :)
@guildem Thanks for your work, I'll clean up the code and merge it as soon a I've been added as a maintainer, I also really want to use this feature.

**Comment by guildem** [comment]
@thosakwe if @insidewhy becomes maintainer, this PR will be merged in it's own updated version I think, no need to merge it for now, thanks for the answer !
@insidewhy let me know if you need anything from me when you'll be ready, and if you can, let me know when you'll have all your changes merged, so I can update my vimrc to point this repo (or another ?). thanks !

**Comment by insidewhy** [comment]
@guildem Cool, I have a few other improvements to the attach implementation also, which I'm sharing with the run implementation. For example it's possible to keep the buffer hidden even without `set hidden` and I also want to be able to change how the logs are open by default (i.e. not `split` or `hidden`, the existing `hidden` functionality also doesn't work on neovim).

**Comment by guildem** [comment]
@insidewhy sounds great ! here is my proposal : you merge all your current and next changes, including parts or all of my current PR, you do the tests on neovim, and when it's done, you tell me and I'll do the tests on vim to check that all is working ok here too.

**Comment by insidewhy** [comment]
@guildem Thanks for your support! Are you using vim or neovim?

**Comment by guildem** [comment]
@insidewhy vim only, never tried neovim

**Comment by insidewhy** [comment]
@guildem Two birds with one stone ☺️

**Comment by insidewhy** [comment]
@guildem I've implemented this now in my repo, you can use `insidewhy/vim-flutter` to target it. You can use

```vim
let g:flutter_show_log_on_attach = 0
```

To not open the log by default, this should work even without `set hidden` now.

**Comment by insidewhy** [comment]
BTW the commit that implements this is here:

https://github.com/insidewhy/vim-flutter/commit/2c45035713f8b5c1446026f97d4d4673c6ac940e

**Comment by insidewhy** [comment]
This functionality is upstream now.

**Comment by guildem** [comment]
Nice way to merge the 2 methods !

**Comment by insidewhy** [comment]
@guildem Thanks! Sorry you didn't get credit on GitHub for the work 😔 I had to redo it to avoid duplication of code.

**Comment by guildem** [comment]
@insidewhy no worries ;-) don't bother, keep it like this !

**Pull request closed without merging**
